version: '3'

networks:
    k-net:

services:

    # nginx
    nginx-service:
        image: nginx:stable-alpine
        container_name: nginx-k-net-container
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www/tokyo
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php82-service
            - mysql8-service
        networks:
            - k-net

    # php
    php82-service:
        build:
            context: .
            dockerfile: ./php/Dockerfile
        container_name: php82-k-net-container
        ports:
            - "9000:9000"
        volumes:
            - ./:/var/www/tokyo
        networks:
            - k-net

    # mysql
    mysql8-service:
        image: mysql:8
        container_name: mysql8-k-net-container
        ports:
            - "3306:3306"
        volumes:
            - ./mysql:/var/lib/mysql
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        #restart: always # always restart unless stopped manually
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_PASSWORD: secret
        networks:
            - k-net

    rabbitmq:
        image: rabbitmq:management
        ports:
            - "5672:15672"
        networks:
            - k-net

    redis:
        image: redis:latest
        container_name: redis-k-net-container
        ports:
            - 6379:80
        command: ["redis-server", "--appendonly", "yes"]
        volumes:
            - redis-data:/data
        networks:
            - k-net

    redis-commander:
        image: rediscommander/redis-commander:latest
        environment:
            - REDIS_HOSTS=local:redis:6379
            - HTTP_USER=root
            - HTTP_PASSWORD=qwerty
        ports:
            - 8060:8081
        depends_on:
            - redis
        networks:
            - k-net

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: k-net-phpmyadmin
        environment:
            PMA_HOST: mysql8-service
        links:
            - mysql8-service
        ports:
            - "8081:80"
        networks:
            - k-net

volumes:
    redis-data: